### ISSUE TITLE
Players can join the Game

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/tg-core#3]
**What has to be done:**
   * Create a Game
   * Create several Players
   * Players ask the Game if there are available Actions. Only one Action should be available to take - Join the Game
   * Players take the selected Action

**How to test:**
   * When a Player joins the Game, the Players count increases by one.
   * Game contains the list of joined Players (?)

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#6](https://github.com/nergal-perm/tg-engine/issues/6) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 5 puzzles [#10](https://github.com/nergal-perm/tg-core/issues/10), [#11](https://github.com/nergal-perm/tg-core/issues/11), [#12](https://github.com/nergal-perm/tg-core/issues/12), [#13](https://github.com/nergal-perm/tg-core/issues/13), [#9](https://github.com/nergal-perm/tg-core/issues/9) are still not solved.
