### ISSUE TITLE
Implement single User and an empty Lobby case

### ISSUE THREAD

**Issue by 0pdd** [nergal-perm/tg-core#45]
Given:
- a Lobby without any Table
- an User

When:
- Lobby connects an User

Then:
- an User receives an empty collection of available Tables

Part of the story #15

**Comment by 0pdd** [comment]
@nergal-perm please pay attention to this new issue.

**Comment by nergal-perm** [comment]
Given:
- a Lobby without any Table
- an User

When:
- Lobby connects an User

Then:
- an User receives an empty collection of available Tables
