### ISSUE TITLE
ManifestTabletopEngineTests.class.st:3: Add GameFactory...

### ISSUE THREAD

**Issue by 0pdd** [nergal-perm/tg-core#6]
The puzzle `3-b2bd08e1` from #3 has to be resolved: 

https://github.com/nergal-perm/tg-engine/blob/f29edaa3c8a7876822b46aea1ea0d3c286574c5d/src/Tabletop-Engine-Tests/ManifestTabletopEngineTests.class.st#L3-L3

The puzzle was created by nergal-perm on 12-Dec-20. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by nergal-perm** [comment]
Duplicated as #13 by 0pdd re-run
